create database CLINICA;
use CLINICA;

CREATE TABLE tblLOGIN (
	id int(11) PRIMARY KEY NOT NULL auto_increment,
	USUARIO char(20) NOT NULL,
    SENHA char(50) NOT NULL
);

CREATE TABLE tblMEDICO(
	ID INT(22) PRIMARY KEY NOT NULL auto_increment,
    NOME_MEDICO VARCHAR(50) NOT NULL,
    FUNCAO_MEDICO VARCHAR(50) NOT NULL,
    CRM_MEDICO_UF CHAR(2) NOT NULL,
    CRM_MEDICO VARCHAR(50),
    CRN_MEDICO VARCHAR(50)
);

CREATE TABLE tblAGENDA(
	ID_AGENDAMENTO INT(10) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME_MEDICO VARCHAR(50) NOT NULL,
    DATA_AGENDAMENTO DATE NOT NULL,
    HORA_AGENDAMENTO TIME NOT NULL
);
